language: python

services:
  - redis-server

cache:
  directories:
  - $HOME/.cache/pip

install:
  - 'pip install git+https://github.com/eve-basil/common.git'
  - 'pip install -r requirements.txt'
  - 'pip install -r test-requirements.txt'

script:
  - 'flake8 basil'
  - 'py.test tests'

env:
  global:
    - REDIS_HOST=localhost

matrix:
  include:
    - python: '2.7'

notifications:
  email: false

git:
  depth: 3

sudo: false